name: Generate Images for Tags

on:
  pull_request:
    branches:
      - main  # Specify the branches you want this action to run on

jobs:
  generate-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' 

    - name: Install dependencies
      run: |
        npm install
 
    - name: Generate images
      run: |
        node CreateTagThumbs.cjs  # Replace with the path to your script
      env:
        NODE_ENV: production

    - name: Commit and push generated images
      uses: EndBug/add-and-commit@v9
      with:
        add: 'public/tag_thumbs' 
        message: 'Add generated images from GitHub Actions'
