name: formatting-check

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read

jobs:
    check:
        name: Check formatting with Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - uses: oven-sh/setup-bun@v2

            - run: bun install
            - run: bun prettier --check .
