name: formatting-check

on: [pull_request, push]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

    check:
        name: Check formatting with Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: oven-sh/setup-bun@v2
            - run: bun install
            - run: bun prettier --dry --check .
